version: '2'

services:
    mariadb:
        image: docker.io/bitnami/mariadb:10.6
        ports:
            - '3306:3306'
        volumes:
            - 'mariadb_data:/bitnami/mariadb'
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_DATABASE=${DB_DATABASE}
    myapp:
        image: docker.io/bitnami/laravel:9
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=mariadb
            - DB_PORT=${DB_PORT}
            - DB_USERNAME=${DB_USERNAME}
            - DB_DATABASE=${DB_DATABASE}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - './:/app'
        depends_on:
            - mariadb
volumes:
    mariadb_data:
        driver: local
